### ISSUE TITLE
TODO: Add more sections

### ISSUE THREAD

**Issue by seisman** [seisman/cv#5]
- [ ] Departmental or institutional services
- [x] Supervised Students d88b4e4f1fe08537caf4c6d6c8112e6dd8a504a0
- [x] Teaching f2691f7644000644eb0e1ebf246de587701efa39
